# Site settings
title: Deep Learning Blog
email: 
description: "Deep Learning Tutorials"
baseurl: ""
url: "https://samiitj.github.io/"
twitter_username: Satyam8989
github_username:  sam-iitj

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
