# Site settings
title: Satyam Saxena blog
email: 
description: "Deep Learning Tutorials"
baseurl: ""
url: "https://samiitj.github.io/"
twitter_username: samiitj
github_username:  samiitj

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
